### ISSUE TITLE
Fix geturls plugin

### ISSUE THREAD

**Issue by gregstoll** [gregstoll/gallery2#98]
It's attached [here](https://github.com/gregstoll/gallery2/issues/96#issuecomment-1336308729) /cc:@Turk1701

**Comment by gregstoll** [comment]
OK, I made some fixes and it seems to work now. I went ahead and just added it to the `modules` directory here - can you try it out @Turk1701?

**Comment by Turk1701** [comment]
Awesome it works. But I swear there used to be an item action for it when viewing an Album. Semi unrelated I have no actions listed in the Plugin list in the Gallery Admin section.

**Comment by Turk1701** [comment]
Item actions work for this. It's the Show URL's in Album view. It's just not doing anything when I click them. This is a very minor thing really in the scope of things. I'm just that lazy.

By the way, thanks for the hard work you do for this.

**Comment by gregstoll** [comment]
Ok, I'll take a look when I can, probably won't be hard to fix.

Thanks 🙂

**Comment by gregstoll** [comment]
OK, I think [commit b64ba0f3](https://github.com/gregstoll/gallery2/commit/b64ba0f38e181f595092251312b08d48884b239a) should fix this - give it a try and let me know!

**Comment by Turk1701** [comment]
Sorry still doesn't do anything when I try to click the plus sign.

**Comment by gregstoll** [comment]
Oh, I think I was looking at something else - what's the plus sign you're clicking? (can you attach a screenshot?)

**Comment by Turk1701** [comment]
https://i.imgur.com/VFLJOIq.png
It works for guests too, if you want to check it out yourself.
https://www.hotelblues.com/gallery2/misc/hotelblues-2022/

**Comment by gregstoll** [comment]
Ah, OK, I think I see what's happening here. The plus sign (now that I found how to turn it on!) works on my site (for example [https://gregstoll.dyndns.org/gallery2/v/randomQ32022/](https://gregstoll.dyndns.org/gallery2/v/randomQ32022/), but it's not working on yours because loading the Javascript file is failing.

That's because your site is served over HTTPS (which is good!) but it's trying to load a script from HTTP. Specifically, the line

```
<script type="text/javascript" src="http://www.hotelblues.com/gallery2/main.php?g2_view=core.CombinedJavascript&amp;g2_key=7f498cd04e109a338734ba5c32ac44de"></script>
```
has the javascript that makes this work, but note that it starts with "http" instead of "https". Modern browsers won't allow doing this for security reasons.

So I would look at `config.php` in your install and look for anything that starts with "http://" and change it to "https://".

(FWIW this may be causing some other stuff to break, too...)

Let me know how it goes!

**Comment by Turk1701** [comment]
Haha, well that was an easy fix. I've got a few other things I've noticed. How many of these issues do you want reported?

This by the way fixed my issue with not having links in the plugins page I mentioned.

**Comment by gregstoll** [comment]
Great, glad that fixed it!

Feel free to file everything, I'll be happy to take a look as I can!
